// ui constant
export const PAGE_LOADING = 'PAGE_LOADING'
export const BUTTON_LOADING = 'BUTTON_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_SINGLE_POST_SUCCESS = 'FETCH_SINGLE_POST_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'
export const FETCH_MEDIA = 'FETCH_MEDIA'
export const CREATE_POST = 'CREATE_POST'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'


export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const SET_USER_ERRORS = 'SET_USER_ERRORS'
export const USER_REGISTER = 'USER_REGISTER'
export const AVATAR_LOADING = 'AVATAR_LOADING'

export const SITE_URL = 'http://localhost/grofers/'